name: Main

on: workflow_dispatch

env:
  TAG_REPO: "harbor.test.dely.io/test/sample"
  TAG_NAME: "harbor.test.dely.io/test/sample:${{ github.sha }}"
  HARBOR_URL: "https://harbor.test.dely.io"
  REMOTE_USERN: "root"
  REMOTE_HOST_IP: "165.227.143.85"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Build docker image'
      run: |
        docker build -t $TAG_NAME .
    - name: 'Login to Harbor'
      run: |
        echo ${{ secrets.HARBOR_SA }} | base64 -d > ./robot.json;
        username=$(cat robot.json | jq -r .name)
        password=$(cat robot.json | jq -r .secret)
        echo "$password" | docker login ${{ env.HARBOR_URL }} --username "$username" --password-stdin
    - name: 'Push to Harbor registry'
      run: |
        docker tag $TAG_NAME $TAG_REPO:latest
        docker push $TAG_NAME
        docker push $TAG_REPO:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Add key'
      run: |
        mkdir -p /home/runner/.ssh;
        echo ${{ secrets.NODE_PRIVATE_KEY }} | base64 -d > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa
        ssh-add
        ssh-keyscan -H ${{ secrets.REMOTE_HOST }} > /home/runner/.ssh/known_hosts
        echo "====> $(pwd)"
        echo "====> $(whoami)"
        echo "=========================="
        cat /home/runner/.ssh/known_hosts
    - name: Create docker context
      run: |
        docker context create remote \
            --description "Docker remote test" \
            --docker "host=ssh://${{ env.REMOTE_USERN }}@${{ env.REMOTE_HOST_IP }}";
    - name: Login to Harbor
      run: |
        echo "${{ secrets.HARBOR_SA }}" | base64 -d > ./robot.json;
        username=$(cat robot.json | jq -r .name)
        password=$(cat robot.json | jq -r .secret)
        echo "===========> $(docker -v)"
        docker context use remote;
        docker context ls;
        docker login ${{ env.HARBOR_URL }} --username "$username" --password "$password"
    - name: Stop existing container
      run: |
        docker context use remote
        docker container stop test | true;
        docker container rm test | true
    - name: Run new version
      run: |
        docker context use remote
        docker run -d -p 3000:3000 --name test $TAG_NAME